{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Count of events that have been observed for the base metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds_count{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The number of events logged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "engine_daemon_events_total{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scrape_samples_post_metric_relabeling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "scrape_samples_post_metric_relabeling{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The total number of failed health checks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "engine_daemon_health_checks_failed_total{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative counters for the observation buckets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "etcd_snap_db_save_total_duration_seconds_bucket{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current number of scrapes being served.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_in_flight",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Information about the Go environment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "go_info{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The number of current subscribers to events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "engine_daemon_events_subscribers_total{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Information related to the swarm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "swarm_node_info{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "up{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scrape_samples_scraped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "scrape_samples_scraped{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of triggered image builds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "builder_builds_triggered_total{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of log entries which are larger than the log buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "logger_log_entries_size_greater_than_buffer_total{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "he number of seconds it takes to call functions gathering info about the host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "engine_daemon_host_info_functions_seconds_sum{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "engine_daemon_health_checks_failed_total{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of events that have been observed for the histogram metric ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "engine_daemon_container_actions_seconds_count{job=\"my-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}